### ISSUE TITLE
Are Wildcard Certificates http-01 challenges possible?

### ISSUE THREAD

**Issue by newalphamedia** [skoerfgen/ACMECert#11]
Hi, is it possible to request a certificate with http-01 challenges which includes many certificates in one?

For example: website.com, *.website.com, *.sub1.website.com, *.sub2.website.com, *.sub3.website.com

Thank you

**Comment by cpu** [comment]
Hi @newalphamedia,

> Hi, is it possible to request a certificate with http-01 challenges which includes many certificates in one?

With Let's Encrypt you can include up to 100 domain names in one certificate.

> For example: website.com, *.website.com, *.sub1.website.com, *.sub2.website.com, *.sub3.website.com

You can't however use any wildcard domain names (those with a `*` prefix) with HTTP-01 using Let's Encrypt. Only DNS-01 challenge types can be used for wildcard domain names.

Hope that helps!

**Comment by newalphamedia** [comment]
Hi @cpu, that helps. Is this a limitation of letsencrypt or your package?

I need to figure out how to request wildcard ssl certificates on my server for which I can only manually enter dns records, because those dns records are not managed by me (pointing to a reverse proxy service). In otherwords, I am in a unique position where the dns does not point to my server’s dns but elsewhere (so dns challenge verification is failing). Does your package have a manual method where I can request the dns challenges with it, manually enter them into the dns settings (through the third party), and then continue? Would that work perhaps? I appreciate your help. I’m also looking at other letsencrypt packages /options but certainly using http-01 would have been easier, it’s a shame that it won’t work for wildcard!
