### ISSUE TITLE
Error in GnuTLS initialization: Failed to acquire random data.

### ISSUE THREAD

**Issue by fbka** [skoerfgen/ACMECert#15]
I'm running identical scripts on two different severs. It's working properly at one server, but on a shared hosting it's running into the following error, whenever trying to create a CSR (_generateCSR_) or key (_generateKey_):

> Error in GnuTLS initialization: Failed to acquire random data.

Both servers are running on PHP version 7.2.29-he.0 and have OpenSSL/1.0.1t enabled. Any ideas of what needs to be enabled/updated/changed on the shared hosting?

**Comment by skoerfgen** [comment]
I assume it has something to do with /dev/*random not being readable.

```
ls -hal /dev/*random
crw-rw-rw- 1 root root 1, 8 Apr  7 20:28 /dev/random
crw-rw-rw- 1 root root 1, 9 Apr  7 20:28 /dev/urandom
```

or there is no entropy available, you can check this with:

```
cat /proc/sys/kernel/random/entropy_avail
```
