### ISSUE TITLE
Two DNS-names in one wildcard certificate

### ISSUE THREAD

**Issue by opiums9** [skoerfgen/ACMECert#17]
Dear Stefan, is it possible to specify two DNS-names in one wildcard certificate? If I write:
```php
$domain_config=array(
  'example.com'=>array('challenge'=>'dns-01'),
  '*.example.com'=>array('challenge'=>'dns-01')
);
```
then it will require me two DNS-TXT records. And also I cannot use this code, it will cause an error:
```php
$domain_config=array(
  'example.com,*.example.com'=>array('challenge'=>'dns-01')
);

```
In certbot, when creating a certificate, you can use the following command, this will add two DNS-names to the certificate:
```sh
certbot certonly --manual --email email@example.com -d *.example.com -d example.com --agree-tos --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory
```
but I don’t understand how to do it in ACMECert?
![image](https://user-images.githubusercontent.com/25082773/79634560-525a9600-8195-11ea-8b29-7edd1cd53345.png)

**Comment by skoerfgen** [comment]
Dear @opiums9,

yes, your first example is correct! It requires indeed two TXT records for the same DNS name (You can have multiple TXT records in place for the same name).

ACMECert will call the challenge callback twice (once for each domain) to set up both TXT records, then it will trigger the validation and finally both remove callbacks are called, like this:

```Triggering challenge callback for *.example.com using dns-01
Triggering challenge callback for example.com using dns-01
Notifying server for validation of *.example.com
Notifying server for validation of example.com
Triggering remove callback for *.example.com
Triggering remove callback for example.com```

**Comment by opiums9** [comment]
Yes it works, thanks!
