### ISSUE TITLE
Basic Authentification / htaccess secured domains + http-01 challenges?

### ISSUE THREAD

**Issue by fbka** [skoerfgen/ACMECert#19]
First of all, thank you so much for developing this awesome tool! I highly appreciate all of you guys putting in the hours of work to make this happen. 

I'm trying to use http-01 challenges on a Basic Authentification (htaccess + htpasswd) secured domain. 

Without any additional efforts, I'm getting the following response. Unfortunately I don't know how to "fix" this.

`Fatal error: Uncaught ACME_Exception: Challenge validation failed: Invalid response from http://_securedomain.tld_/.well-known/acme-challenge/2DPe2qEWB4LEYLJqJFRhdRooDJAlDXUBVzpeYxTjX3o [2a01:488:42:1000:b24d:6bf2:fff9:445d]: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n  \"http://www.w3.org/TR/xhtml1/D" (urn:ietf:params:acme:error:unauthorized) in /is/htdocs/.../ACMECert/ACMECert.php:220`

PS: Edited out the exact path and domain info for security reasons.

**Comment by skoerfgen** [comment]
Thank you for your kind words!

Unfortunately Let's Encrypt does not support HTTP Authentication for the validation requests.

You could use another challenge type or configure an exception for the authentication for the `/.well-known/acme-challenge/` path like this:

> Apache
```
<Directory /var/www/mywebsite.com/www/.well-known>
    Require all granted
</Directory>
```

> Nginx
```
location /.well-known/acme-challenge {
    auth_basic off;
}
```
