### ISSUE TITLE
dns-01 issue

### ISSUE THREAD

**Issue by thk12** [skoerfgen/ACMECert#2]
there is a small TTL delay between 2 DNS requests to the identical zone. this is an issue if your're going to sign a certificate for a domain AND a wildcard.

so when you set up the first TXT record for *.example.com and LE will validate it, the second validation for example.com will fail, because LE resolver still has only the TXT record for the first request in cache

Fix: you should be able to set up all TXT records for a zone and THEN fire the validation request

// example code
// (replaced my domain with example.com in code and log)
$ac=new ACMECert(false);
$ac->loadAccountKey('file://account_key.pem');
$privkey=$ac->generateRSAKey();
$domain_config=array(
  'example.com'=>array('challenge'=>'dns-01'),
  '*.example.com'=>array('challenge'=>'dns-01')
);
$handler=function($opts) use ($ac){
        echo 'Create DNS-TXT-Record '.$opts['key'].' with value '.$opts['value']."\n";
	// code to set up DNS TXT record
        return function($opts){
             // code to remove this TXT record
        };
};
$fullchain=$ac->getCertificateChain($privkey,$domain_config,$handler);

// log:
Generating CSR
Getting account info
Initializing ACME v2 staging environment
  https://acme-staging-v02.api.letsencrypt.org/directory [200 OK] (0.35s)
Initialized
  https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce [200 OK] (0.32s)
  https://acme-staging-v02.api.letsencrypt.org/acme/new-acct [200 OK] (0.23s)
AccountID: https://acme-staging-v02.api.letsencrypt.org/acme/acct/118150
Account info retrieved
Creating Order
  https://acme-staging-v02.api.letsencrypt.org/acme/new-order [201 Created] (2.16s)
Order created: https://acme-staging-v02.api.letsencrypt.org/acme/order/118150/24075821
Fetching authorization (1/2)
  https://acme-staging-v02.api.letsencrypt.org/acme/authz/cMwkKLmHSg2pAXGcwsd_10531NhE3_hz05TXkM822e8 [200 OK] (0.24s)
Triggering challenge callback for example.com [dns-01]
Create DNS-TXT-Record _acme-challenge.example.com with value cpFMEUlL6CcefDIiSsiMlhCCcrihB0-mh2rqAwSa4WE
Notifying server for validation
  https://acme-staging-v02.api.letsencrypt.org/acme/challenge/cMwkKLmHSg2pAXGcwsd_10531NhE3_hz05TXkM822e8/251283352 [200 OK] (0.25s)
Waiting for server challenge validation
  https://acme-staging-v02.api.letsencrypt.org/acme/authz/cMwkKLmHSg2pAXGcwsd_10531NhE3_hz05TXkM822e8 [200 OK] (0.24s)
Validation successful: example.com
Fetching authorization (2/2)
  https://acme-staging-v02.api.letsencrypt.org/acme/authz/Kw4FP2B5oQPq-XUigqcE6wkO662pIqhJMsKcmbCYE88 [200 OK] (0.23s)
Triggering challenge callback for *.example.com [dns-01]
Create DNS-TXT-Record _acme-challenge.example.com with value okw-z8Pz5bda50LleTR8S_hv9W_s1xTdSKBINucQNgA
Notifying server for validation
  https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Kw4FP2B5oQPq-XUigqcE6wkO662pIqhJMsKcmbCYE88/251283351 [200 OK] (0.24s)
Waiting for server challenge validation
  https://acme-staging-v02.api.letsencrypt.org/acme/authz/Kw4FP2B5oQPq-XUigqcE6wkO662pIqhJMsKcmbCYE88 [200 OK] (0.24s)
Validation failed: *.example.com
PHP Fatal error:  Uncaught exception 'Exception' with message 'Challenge validation failed: Incorrect TXT record "cpFMEUlL6CcefDIiSsiMlhCCcrihB0-mh2rqAwSa4WE" found at _acme-challenge.example.com (urn:ietf:params:acme:error:unauthorized)' in ACMECert.php:178
Stack trace:
#0 acmev2.php(98): ACMECert->getCertificateChain('-----BEGIN PRIV...', Array, Object(Closure))
#1 {main}
  thrown in ACMECert.php on line 178

Fatal error: Uncaught exception 'Exception' with message 'Challenge validation failed: Incorrect TXT record "cpFMEUlL6CcefDIiSsiMlhCCcrihB0-mh2rqAwSa4WE" found at _acme-challenge.example.com (urn:ietf:params:acme:error:unauthorized)' in ACMECert.php:178
Stack trace:
#0 acmev2.php(98): ACMECert->getCertificateChain('-----BEGIN PRIV...', Array, Object(Closure))
#1 {main}
  thrown in ACMECert.php on line 178

**Comment by skoerfgen** [comment]
Thank you for reporting this issue!

In version [1.2](https://github.com/skoerfgen/ACMECert/tree/v1.2) this issue should be resolved.

(I implemented the fix you suggested)

**Comment by skoerfgen** [comment]
Update: Make sure to get the latest release [1.4](https://github.com/skoerfgen/ACMECert/tree/v1.4)
It fixes a bug in v1.2 and v1.3
