### ISSUE TITLE
At which point is file cert_private_key.pem created? 

### ISSUE THREAD

**Issue by cosmomathieu** [skoerfgen/ACMECert#23]
At which point is file `cert_private_key.pem` created? I keep getting an error that `cert_private_key.pem` doesn't exist: 

```
$fullchain=$ac->getCertificateChain('file://'.'cert_private_key.pem',$domain_config,$handler);
file_put_contents('fullchain.pem',$fullchain);
```

Is this something I need to create manually? I seem to be missing something.

**Comment by skoerfgen** [comment]
ACMECert does not generate keys automatically. [`getCertificateChain`](https://github.com/skoerfgen/ACMECert#acmecertgetcertificatechain) expects the first paramter to be an already existing file.

So you have to generate the key before using it. You can use [`generateRSAKey`](https://github.com/skoerfgen/ACMECert#acmecertgeneratersakey) or [`generateECKey`](https://github.com/skoerfgen/ACMECert#acmecertgenerateeckey) for this.

**Comment by cosmomathieu** [comment]
So in short create two keys, 1) `acount_key.pem` for registering your account with LE, and 2) `cert_private_key.pem` for use in getting the certificate chain. Am I on the right track? If so, would you recommend generating a `cert_private_key.pem` per domain?

**Comment by skoerfgen** [comment]
> So in short create two keys, 1) `acount_key.pem` for registering your account with LE, and 2) `cert_private_key.pem` for use in getting the certificate chain. Am I on the right track?

Yes, you are!


> If so, would you recommend generating a `cert_private_key.pem` per domain?


That depends on your use case.

For example: If you are hosting multiple different customers (each having their own domains), it makes sense to generate a new key for each domain to separate them.

On the other hand, if it is for you own server (having multiple domains) I don't see a reason why not to use the same key for all domains. In this case you could even generate only one certificate for all domains. (There can be up to 100 domains in one certifcate)

**Comment by cosmomathieu** [comment]
Thank you! This was really helpful. I'm closing this issue.
