### ISSUE TITLE
.pem to .crt and .key

### ISSUE THREAD

**Issue by rajnisheu** [skoerfgen/ACMECert#25]
Hi,

Thanks for this great library. Was able to get to the end and get a `fullchain.pem` file.

I need a .crt and .key file for apache, and not able to figure out how to get that.

Tried the following two:
```
openssl rsa -in fullchain.pem -out keyfileOutName.key
openssl pkey -in fullchain.pem -out foo.key
```

but get an error:
```
unable to load key
648:error:0906D06C:PEM routines:PEM_read_bio:no start line:.\crypto\pem\pem_lib.c:701:Expecting: ANY PRIVATE KEY
```

Any help greatly appreciated.

**Comment by skoerfgen** [comment]
Hi,

for Apache (version >= 2.4.8) you could configure it this way:
```apache
SSLCertificateFile fullchain.pem
SSLCertificateKeyFile cert_private_key.pem
```

assuming you used something like this:

```php
$fullchain=$ac->getCertificateChain('file://'.'cert_private_key.pem',$domain_config,$handler);
file_put_contents('fullchain.pem',$fullchain);
```

there should be no need to split fullchain.pem into separate files.

(fullchain.pem does not contain the private key. the .key file is what you passed as first argument to the [getCertificateChain ](https://github.com/skoerfgen/ACMECert#acmecertgetcertificatechain) function.)

Does this solve the problem?

**Comment by rajnisheu** [comment]
@skoerfgen Many thanks for your quick response, and your help!

yes, that worked perfectly 👍
