### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Bizarrus** [skoerfgen/ACMECert#3]
Please provide some examples!

**Comment by skoerfgen** [comment]
Have you seen [Usage Examples](https://github.com/skoerfgen/ACMECert#usage-examples) and especially [Get Certificate using http-01 challenge](https://github.com/skoerfgen/ACMECert#get-certificate-using-http-01-challenge) ?


Or is it unclear which steps to perform in which order?

**Comment by Bizarrus** [comment]
Yep, for a sample, how i can take a renew?

The other steps like requesting/creating and revoking are works perfectly.

**Comment by skoerfgen** [comment]
To renew a certificate just get a new one.
(Just repeat the steps that you used to get the certificate in the first place.)

**Comment by Bizarrus** [comment]
But this is against the specifications: https://letsencrypt.org/docs/rate-limits/

**Comment by skoerfgen** [comment]
The "official" way of renewing a certificate is to get a new one.
There isn't even a funtion in the ACME-Protocol for renewals.


The rate limits you mentioned are just in place to avoid overloading the system.

Related: https://community.letsencrypt.org/t/renew-certificate-without-cerbot/76580

**Comment by Bizarrus** [comment]
Whats the best way for a renewing process?

- revoke the previous certificate?
- generate new pricate key or use the old once?

**Comment by skoerfgen** [comment]
- Revocation is not necessary, from a security point of view, if the private key is not compromised. https://letsencrypt.org/docs/revoking/
- If the private key is not compromised/bad, there is little technical reason to change it, on the other hand doesn't it hurt to change it. https://security.stackexchange.com/q/27810

**Comment by Bizarrus** [comment]
Thanks yor your feedback :)
