### ISSUE TITLE
Deprecated function on PHP8

### ISSUE THREAD

**Issue by KatsuroKurosaki** [skoerfgen/ACMECert#32]
Hi,

I recently upgraded my PHP installation to php 8 and the function openssl_pkey_free() triggers a deprecated message.

Thank you

**Comment by skoerfgen** [comment]
Hello,

thank you for reporting this issue! I have just released a fix.

**Comment by KatsuroKurosaki** [comment]
Hello!

Thanks a lot for the quick fix, keep being awesome!  😊
